todo:
  '1':
    ==: org.bukkit.inventory.ItemStack
    v: 2586
    type: WRITTEN_BOOK
    meta:
      ==: ItemMeta
      meta-type: BOOK_SIGNED
      title: Check
      author: Bunny
      pages:
        - '{"text":"Text for test"}'
