todo:
  '1':
    ==: org.bukkit.inventory.ItemStack
    v: 2586
    type: WRITTEN_BOOK
    meta:
      ==: ItemMeta
      meta-type: BOOK_SIGNED
      title: Проверка
      author: S1esta
      pages:
        - '{"text":"Текст для проверки"}'
