todo:
  test:
    ==: org.bukkit.inventory.ItemStack
    v: 2586
    type: WRITTEN_BOOK
    meta:
      ==: ItemMeta
      meta-type: BOOK_SIGNED
      title: Проверка
      author: S1esta
      pages:
        - '{"text":"Это для теста\nабобаабоба\nабоба\nабобаабоба\nабоба\nабобаабоба\nабоба\nабобаабоба\nабоба\nабобаабоба\nабоба\nабобаабоба\nабоба\n\n"}'
        - '{"text":"абобаабоба\nабоба\nабобаабоба\nабоба\nабобаабоба\nабоба\nабобаабоба\nабоба\nабобаабоба\nабоба\nабобаабоба\nабоба\nабобаабоба\nабоба\n"}'
        - '{"text":"абобаабоба\nабоба\nабобаабоба\nабоба\nабобаабоба\nабоба\nабобаабоба\nабоба\nабобаабоба\nабоба\nабобаабоба\nабоба\nабобаабоба\nабоба\n"}'


